source 'https://rubygems.org'


gem 'rmagick', '~> 2.16.0'
gem 'cocoon'
# gem 'nested_form_fields'
gem 'pg_search'
gem 'devise'
gem 'paperclip', "~> 5.1.0"
gem 'aws-sdk'
gem 'materialize-sass'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'

group :development, :test do
 	gem 'pry-rails'
 	gem 'pry-byebug'
	gem 'better_errors'
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
